### ISSUE TITLE
Button redesign because i felt like it :D

### ISSUE THREAD

**Issue by cozyton** [TechStudent10/PositionSwitchMod#1]
![startposBtn](https://github.com/user-attachments/assets/3fda4720-3649-4fe6-b190-e240666b0d5c)

**Comment by TechStudent10** [comment]
I like it :D


ask Jay to make a logo for it........

**Comment by cozyton** [comment]
![startposBtn 3](https://github.com/user-attachments/assets/84319092-ff22-4a39-bb4b-389325a5b5fb)
availax complained about this notsuiting the vanilla textures, which was very fair criticism so i made it look a lot more like the copy button, and i think this is far better. i dont think jay has woken up yet but ill let u know if/when they make a logo :D, glad to see you're still modding

**Comment by cozyton** [comment]
![startposBtn 4 FINAL PLEASE](https://github.com/user-attachments/assets/bba45b4f-ceeb-4a7a-b8fe-77e0a0e80c05)

ok promise this is the last version please maybe hopefully if availax doesnt randomly log on and make me reconsider my choices

**Comment by DasshuDev** [comment]
@TechStudent10 :0

**Comment by TechStudent10** [comment]
@JayDasshu hey what's good! please make a better logo I can't design for the love of me-

**Comment by TechStudent10** [comment]
> ok promise this is the last version please maybe hopefully if availax doesnt randomly log on and make me reconsider my choices

LOL alright thanks for the help

**Comment by DasshuDev** [comment]
![Asset 1](https://github.com/user-attachments/assets/777b9652-4b8e-47fc-adf7-0f180f9ae8ee)
@TechStudent10 :3

**Comment by TechStudent10** [comment]
> @TechStudent10 :3

GOAT thank you so much

**Comment by DasshuDev** [comment]
im gonna make a better variant and a completely different logo in due time, im tired and wanna eep lol

glad u like it tho! :D

**Comment by TechStudent10** [comment]
> im gonna make a better variant and a completely different logo in due time, im tired and wanna eep lol
> 
> glad u like it tho! :D

o ill be waiting then!

**Comment by DasshuDev** [comment]
![Asset 2](https://github.com/user-attachments/assets/25ad0934-7fbb-4d3b-baa1-6a9e71f61e4a)
concep t2 :3 @TechStudent10 @Crooozy

**Comment by TechStudent10** [comment]
I really should be asleep but I think if the startpos text was smaller and fit on the page (i.e. on the top of the page) then it'd look nicer, but epic rn

**Comment by DasshuDev** [comment]
![Asset 3](https://github.com/user-attachments/assets/b1fcf453-84b0-4197-9594-12645f04aa89)
womp

**Comment by TechStudent10** [comment]
all redesigns have been added :D
